export const PREDEFINED_SKILLS = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "C++",
  "C",
  "Scala",
  "Elixir",
  "Clojure",
  "Haskell",
  "Perl",
  "Objective-C",
  "Dart",
  "Lua",
  "R",
  "SQL",
  "Groovy",
  "F#",
  "Bash/Shell Scripting",
  "PowerShell",

  // Frontend Frameworks & Libraries
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "Remix",
  "Astro",
  "SolidJS",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Alpine.js",
  "Lit",
  "Stencil",
  "HTML5",
  "CSS3",
  "Sass",
  "LESS",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "Bulma",
  "Styled Components",
  "Emotion",
  "Webpack",
  "Vite",
  "Parcel",
  "Rollup",
  "Babel",
  "Redux",
  "Zustand",
  "Jotai",
  "Recoil",
  "MobX",
  "RxJS",
  "D3.js",
  "Three.js",
  "WebAssembly",

  // Backend Frameworks & Libraries
  "Node.js",
  "Express.js",
  "Koa.js",
  "NestJS",
  "Fastify",
  "Spring Boot",
  "Spring Framework",
  "Quarkus",
  "Micronaut",
  "Jakarta EE",
  "Java EE",
  "Django",
  "Flask",
  "FastAPI",
  "Ruby on Rails",
  "Sinatra",
  "Phoenix",
  "ASP.NET Core",
  "ASP.NET MVC",
  ".NET", // Added generic .NET
  "Laravel",
  "Symfony",
  "CodeIgniter",
  "CakePHP",
  "Gin",
  "Echo",
  "Actix",
  "Rocket",
  "Play Framework",
  "Akka",

  // Databases & Data Stores
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "Microsoft SQL Server",
  "Oracle Database",
  "SQLite",
  "MongoDB",
  "Redis",
  "Cassandra",
  "Couchbase",
  "DynamoDB",
  "Cosmos DB",
  "Firebase Realtime Database",
  "Firestore",
  "Elasticsearch",
  "Solr",
  "Neo4j",
  "ArangoDB",
  "InfluxDB",
  "TimescaleDB",
  "Memcached",

  // Cloud Platforms & Services
  "Amazon Web Services",
  "AWS EC2",
  "AWS S3",
  "AWS Lambda",
  "AWS RDS",
  "AWS DynamoDB",
  "AWS SQS",
  "AWS SNS",
  "AWS API Gateway",
  "AWS CloudFront",
  "AWS EKS",
  "AWS ECS",
  "AWS VPC",
  "AWS IAM",
  "AWS CloudFormation",
  "AWS CDK",
  "Microsoft Azure",
  "Azure Virtual Machines",
  "Azure Blob Storage",
  "Azure Functions",
  "Azure SQL Database",
  "Azure Cosmos DB",
  "Azure Service Bus",
  "Azure API Management",
  "Azure CDN",
  "Azure AKS",
  "Azure Container Instances",
  "Azure VNet",
  "Azure AD",
  "Azure ARM Templates",
  "Azure Bicep",
  "Google Cloud Platform",
  "GCP Compute Engine",
  "GCP Cloud Storage",
  "GCP Cloud Functions",
  "GCP Cloud SQL",
  "GCP Firestore",
  "GCP Pub/Sub",
  "GCP API Gateway",
  "GCP Cloud CDN",
  "GCP GKE",
  "GCP Cloud Run",
  "GCP VPC",
  "GCP IAM",
  "GCP Cloud Deployment Manager",
  "Heroku",
  "DigitalOcean",
  "Vercel",
  "Netlify",
  "Fly.io",
  "Render",
  "Oracle Cloud Infrastructure",
  "IBM Cloud",

  // DevOps, CI/CD & Infrastructure
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitLab CI/CD",
  "GitHub Actions",
  "Azure DevOps Pipelines",
  "AWS CodePipeline",
  "AWS CodeBuild",
  "AWS CodeDeploy",
  "CircleCI",
  "Travis CI",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Pulumi",
  "Helm",
  "Prometheus",
  "Grafana",
  "Datadog",
  "New Relic",
  "Splunk",
  "ELK Stack",
  "Istio",
  "Linkerd",
  "Consul",
  "Vault",
  "Serverless Framework",
  "Infrastructure as Code",
  "GitOps",

  // Mobile Development
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "NativeScript",
  "Ionic",

  // Testing Frameworks & Tools
  "JUnit",
  "TestNG",
  "Mockito",
  "Pytest",
  "Unittest",
  "Jest",
  "Mocha",
  "Cypress",
  "Playwright",
  "Selenium",
  "RSpec",
  "NUnit",
  "xUnit.net",
  "PHPUnit",
  "Postman",
  "Insomnia",
  "LoadRunner",
  "JMeter",
  "K6",

  // Version Control
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Subversion",

  // API & Communication Protocols
  "REST APIs",
  "GraphQL",
  "gRPC",
  "SOAP",
  "WebSockets",
  "JSON",
  "XML",
  "Protocol Buffers",
  "OpenAPI",
  "Swagger",

  // Data Science & Machine Learning
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Jupyter Notebooks",
  "Apache Spark",
  "Hadoop",
  "Machine Learning", // Generic term
  "Data Science", // Generic term

  // Web Servers
  "Nginx",
  "Apache HTTP Server",
  "IIS",
  "Caddy",

  // Messaging & Queuing Systems
  "Apache Kafka",
  "RabbitMQ",
  "ActiveMQ",
  "ZeroMQ",
  "Amazon SQS",
  "Google Pub/Sub",
  "Azure Service Bus",

  // Other Concepts & Tools
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Object-Oriented Programming",
  "Functional Programming",
  "Microservices Architecture",
  "Monolithic Architecture",
  "Domain-Driven Design",
  "Test-Driven Development",
  "Behavior-Driven Development",
  "Web Security",
  "OWASP Top 10",
  "Authentication",
  "Authorization",
  "OAuth",
  "OpenID Connect",
  "SAML",
  "JWT",
  "Blockchain",
  "Smart Contracts",
  "Solidity",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Regular Expressions",
  "System Design",
  "Data Structures",
  "Algorithms",
] as const;
